### ISSUE TITLE
[Suggestion] Adding different options for uploading files to a Vector Database

### ISSUE THREAD

**Issue by v-j-jpg** [MuleSoft-AI-Chain-Project/mule-vectors-connector#12]
Hi everyone, 

I've set up the MAC vectors connector and deployed it to Cloud Hub 2.0. While uploading the files, I noticed that the connector can only read files from a local file path. To do it, I needed to write my files to the `/tmp` folder in Cloud Hub and delete them after the upload. Example of the flow below: 
<img width="337" alt="image" src="https://github.com/user-attachments/assets/3ac27908-e7fe-4fb0-9dbc-dd80b4aed34d">

It would be nice if the connector could offer to directly upload files from for example Azure/AWS bucket/Google Drive.
Since writing in the 'tmp 'folder has its limitations, and since you don't know how much free space there actually is and your files can sometimes be larger, you risk crashing the pod when it runs out of disk space

If the files are already in an S3 bucket the flow would look like this 
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/8bde8cec-edfe-420b-9ca0-1dd129cfd7ff">
which uses a lot of resources instead of loading the files directly

**Comment by amirkhan-ak-sf** [comment]
@v-j-jpg, @alick888 has implemented the S3 bucket file drop for MAC Vectors on the ["add/S3" branch](https://github.com/MuleSoft-AI-Chain-Project/mac-vectors/tree/add/S3). 

Would you mind testing it?
