### ISSUE TITLE
Connector can run/create configuration.

### ISSUE THREAD

**Issue by infopath-mule** [MuleSoft-AI-Chain-Project/mule-vectors-connector#14]
Anypoint Studio - Tooling for Mule Runtime - Version: 7.18.1
=====
Failed to resolve module com.mule.mulechain:mulechain-vectors:0.1.0 (hover for more details or open this problem's Properties)
Resolving dependency com.mule.mulechain:mulechain-vectors found the following exceptions:
java.lang.RuntimeException: There was an issue solving the dependencies for the bundleDescriptors [[BundleDescriptor{groupId='com.mule.mulechain', artifactId='mulechain-vectors', baseVersion='null', version='0.1.0', type='jar', classifier=Optional[mule-plugin], systemPath=Optional.empty}]]
===========
		<dependency>
		    <groupId>com.mule.mulechain</groupId>
		    <artifactId>mulechain-vectors</artifactId>
		    <version>0.1.0</version>
		    <classifier>mule-plugin</classifier>		
		</dependency>

**Comment by alick888** [comment]
Have you downloaded and installed the connector following instructions in this [link](https://mac-project.ai/docs/mulechain-vectors/getting-started).

**Comment by amirkhan-ak-sf** [comment]
@infopath-mule please use the following dependency
`	<dependency>
	    <groupId>com.mule.mulechain</groupId>
	    <artifactId>mulechain-vectors</artifactId>
	    <version>0.1.25</version>
	    <classifier>mule-plugin</classifier>		
	</dependency>`

There was a glitch in the develop > master merge.
