### ISSUE TITLE
Support for Qdrant Vector DB

### ISSUE THREAD

**Issue by amirkhan-ak-sf** [MuleSoft-AI-Chain-Project/mule-vectors-connector#37]
Support for Qdrant Vectors is requested.
More Info: https://qdrant.tech/

**Comment by tbolis-at-mulesoft** [comment]
@amirkhan-ak-sf what about the connector size we need to keep under control?

**Comment by amirkhan-ak-sf** [comment]
Yes, the size need to be under control. We shouldn't exceed the overall size in the mule app of 350 MB. Currently we are at 326.1 MB. @tbolis-at-mulesoft maybe we can think about similar pattern to seperate into 2 connectors (maybe on-premise vs SaaS)?

**Comment by tbolis-at-mulesoft** [comment]
@amirkhan-ak-sf Let's discuss about this after the new version release.

**Comment by tbolis-at-mulesoft** [comment]
Thank you @Anush008 we sull’ look into your PR asap. Is there a trial we can use to test it out? What’s the best option to test it? Thx.

**Comment by Anush008** [comment]
Hey @tbolis-at-mulesoft . Qdrant can run locally using Docker.
I've mentioned the steps in the PR description.

**Comment by tbolis-at-mulesoft** [comment]
Thx awesome.

**Comment by tbolis-at-mulesoft** [comment]
Quick question… does quadrant offer a way to efficiently query all segments (only metadata, no text and vector) using some sort of pagination? When possible we are offering a list sources method. Thx

**Comment by Anush008** [comment]
Yes.
https://qdrant.tech/documentation/concepts/points/#scroll-points
https://api.qdrant.tech/v-1-12-x/api-reference/points/scroll-points

**Comment by tbolis-at-mulesoft** [comment]
Awesome we will need then to implement as well the list source method as done already for others (eg. milvus, ai search, pgvector, …)
Thx

**Comment by Anush008** [comment]
I am running into this super weird issue with my VSCode Java extension completely failing to work on the project.
So that's blocking the list sources update.

**Comment by tbolis-at-mulesoft** [comment]
@Anush008 no problem I'll look into this on Friday.

**Comment by Anush008** [comment]
I switched over to IntelliJ to continue.

**Comment by amirkhan-ak-sf** [comment]
@Anush008 I had the same issue. IntellJ is perfect for Java.

**Comment by Anush008** [comment]
`listSources()` is supported now.
