### ISSUE TITLE
Mac Vector 0.2.50 || Where to configure Azure open AI deployment model name?

### ISSUE THREAD

**Issue by ajaytiwa** [MuleSoft-AI-Chain-Project/mule-vectors-connector#61]
Previously (json way of configuring the connector) we used to provide deployment model name also for Azure OPEN AI models.
but with 0.2.50 version (Open source Release) where to configure this. I think there is no placeholder for this in connector?
Used java 11 to build connector.
@tbolis-at-mulesoft

**Comment by tbolis-at-mulesoft** [comment]
Hi @ajaytiwa, 
I just checked the code that parameter was there in the json, but never used.
The embedding model name can be specified at operation level.
In the below screenshot is the parameter at the bottom.

![image](https://github.com/user-attachments/assets/9e61e575-98b2-4151-bfcf-b962d56cf160)
