### ISSUE TITLE
Make module modular

### ISSUE THREAD

**Issue by tbolis-at-mulesoft** [MuleSoft-AI-Chain-Project/mule-vectors-connector#67]
### **@Import** 

annotation https://docs.mulesoft.com/mule-sdk/latest/subtypes-mapping same used to define OAuth as an extension of HTTP Connector.

### **External Libraries**

Connectors and Modules sometimes depend on external libraries that cannot be packaged inside the connector due to licensing, versioning, custom libs, and so on.

The Database connector is an example of a case where the same base code you can work with several different drivers and several versions of a same driver. The solution to this problem is ask users of the Database connector to identify the JDBC Driver to use for the database to which they want to connect.

**Comment by tbolis-at-mulesoft** [comment]
We need to test this option 
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/6606c716-9811-419d-880e-6ce897219eb5">

**Comment by tbolis-at-mulesoft** [comment]
If we add the provided scope into the connector pom

```
<dependency>
  <groupId>dev.langchain4j</groupId>
  <artifactId>langchain4j-document-loader-amazon-s3</artifactId>
  <version>${langchain4jVersion}</version>
  <scope>provided</scope>
</dependency>
```

this ensures that these libraries are required during compilation but are not included in the final packaged JAR for the connector.

If you do not add in this case the dependency in the mule application JAR, you end up with a

`java.lang.ClassNotFoundException: dev.langchain4j.data.document.loader.amazon.s3.AmazonS3DocumentLoader`

**Comment by tbolis-at-mulesoft** [comment]
<img width="622" alt="image" src="https://github.com/user-attachments/assets/74852f14-578c-4961-a502-f7cf6ed65ca6">

**Comment by tbolis-at-mulesoft** [comment]
230MB
![image](https://github.com/user-attachments/assets/cb1f0170-0959-41f1-a8f9-05cc9b795a84)

vs 330 MB of version v0.2.50

**Comment by tbolis-at-mulesoft** [comment]
We still have class isolation issues we are struggling to solve.

**Comment by amirkhan-ak-sf** [comment]
This Looks very promising! Now i remember that we are doing something similar with jsoup dependency in the mule ai chain connector, but without the external annotations in the config.

Let me find it.

**Comment by amirkhan-ak-sf** [comment]
In the pom.xml of ai chain connector you can find something this...
....
`		<plugin>
				<groupId>com.mulesoft.munit</groupId>
				<artifactId>munit-extensions-maven-plugin</artifactId>
				<version>${munit.extensions.maven.plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<argLines>
						<argLine>
							-javaagent:${settings.localRepository}/org/jacoco/org.jacoco.agent/${jacoco.version}/org.jacoco.agent-${jacoco.version}-runtime.jar=destfile=${session.executionRootDirectory}/target/jacoco.exec,includes=org/mule/extension/mulechain/**
						</argLine>
					</argLines>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>org.jsoup</groupId>
							<artifactId>jsoup</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
`......
`		<dependency>
			<groupId>dev.langchain4j</groupId>
			<artifactId>langchain4j</artifactId>
			<version>${langchain4j.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>jsoup</artifactId>
					<groupId>org.jsoup</groupId>
				</exclusion>
			</exclusions>
		</dependency>`....
....

@arpitg-1 maybe you can get together on a meeting with @tbolis-at-mulesoft  to look into this. Once we solve it in 1 connector we solve it everywhere. It is about dynamically loading dependencies, we have discussed this before with @dipeshkumardutta-sfemu. 

Tommaso had a genius idea similar to the db connector. Please have a look...

**Comment by arpitg-1** [comment]
Sure, @tbolis-at-mulesoft lets connect in today's call for this.
